-- MySQL Script generated by MySQL Workbench
-- Wed May  6 01:46:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `EmployeeID` INT NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EmployeeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Artist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Artist` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Artist` (
  `ArtistID` INT NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `Gender` CHAR(1) NULL,
  `Address` VARCHAR(255) NULL,
  `Insturment` VARCHAR(255) NULL,
  `ManagerID` INT NOT NULL,
  PRIMARY KEY (`ArtistID`),
  UNIQUE INDEX `PhoneNumber_UNIQUE` (`PhoneNumber` ASC) VISIBLE,
  CONSTRAINT `fk_Artist_Employee`
    FOREIGN KEY (`ManagerID`)
    REFERENCES `mydb`.`Employee` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Manager` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Manager` (
  `ManagerID` INT NOT NULL,
  `Royalty` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`ManagerID`),
  CONSTRAINT `fk_Manager_Employee1`
    FOREIGN KEY (`ManagerID`)
    REFERENCES `mydb`.`Employee` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Adminstrative Assistant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Adminstrative Assistant` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Adminstrative Assistant` (
  `AssitantID` INT NOT NULL,
  `Salary` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`AssitantID`),
  CONSTRAINT `fk_Adminstrative Assistant_Employee1`
    FOREIGN KEY (`AssitantID`)
    REFERENCES `mydb`.`Employee` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Contract` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Contract` (
  `ContractID` INT NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NOT NULL,
  `Royalty` DECIMAL(3,2) NOT NULL,
  `Note` TEXT NULL,
  `EmployeeID` INT NOT NULL,
  `ArtistID` INT NOT NULL,
  PRIMARY KEY (`ContractID`),
  CONSTRAINT `fk_Contract_Employee1`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `mydb`.`Employee` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contract_Artist1`
    FOREIGN KEY (`ArtistID`)
    REFERENCES `mydb`.`Artist` (`ArtistID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Review` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Review` (
  `ReviewID` INT NOT NULL,
  `Note` TEXT NULL,
  `EmployeeID` INT NOT NULL,
  `ArtistID` INT NOT NULL,
  PRIMARY KEY (`ReviewID`),
  CONSTRAINT `fk_Contract_Employee10`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `mydb`.`Employee` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contract_Artist10`
    FOREIGN KEY (`ArtistID`)
    REFERENCES `mydb`.`Artist` (`ArtistID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recommendation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Recommendation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Recommendation` (
  `ArtistName` VARCHAR(255) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(255) NULL,
  `YearOfBirth` DATE NULL,
  `Gender` CHAR(1) NULL,
  `Note` TEXT NULL,
  `Instrument` VARCHAR(45) NULL,
  `Degree` VARCHAR(45) NULL,
  `Street` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  `Source` TEXT NOT NULL,
  `ArtistReference` INT NULL,
  PRIMARY KEY (`ArtistName`, `PhoneNumber`),
  CONSTRAINT `fk_Recommendation_Artist1`
    FOREIGN KEY (`ArtistReference`)
    REFERENCES `mydb`.`Artist` (`ArtistID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Expenses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Expenses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Expenses` (
  `ArtistID` INT NOT NULL,
  `Month` CHAR(2) NOT NULL,
  `Year` CHAR(4) NOT NULL,
  `TravelCost` DECIMAL(15,2) NULL,
  `DirectExpenses` DECIMAL(15,2) NULL,
  PRIMARY KEY (`ArtistID`, `Month`, `Year`),
  CONSTRAINT `fk_Expenses_Artist1`
    FOREIGN KEY (`ArtistID`)
    REFERENCES `mydb`.`Artist` (`ArtistID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ArtistCalender`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ArtistCalender` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ArtistCalender` (
  `Artist_ArtistID` INT NOT NULL,
  `TimeOutDate` DATE NOT NULL,
  `Reason` VARCHAR(255) NULL,
  PRIMARY KEY (`Artist_ArtistID`),
  CONSTRAINT `fk_ArtistCalender_Artist1`
    FOREIGN KEY (`Artist_ArtistID`)
    REFERENCES `mydb`.`Artist` (`ArtistID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `CustomerID` INT NOT NULL,
  `CustomerName` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Event` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Event` (
  `EventID` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Street` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  `Status` VARCHAR(45) NOT NULL,
  `CustomerID` INT NOT NULL,
  `ArtistID` INT NOT NULL,
  PRIMARY KEY (`EventID`),
  CONSTRAINT `fk_Event_Customer1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `mydb`.`Customer` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Event_Artist1`
    FOREIGN KEY (`ArtistID`)
    REFERENCES `mydb`.`Artist` (`ArtistID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Invoice` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Invoice` (
  `InvoiceID` INT NOT NULL,
  `Amount` DECIMAL(15,2) NULL,
  `EventID` INT NOT NULL,
  `CustomerID` INT NOT NULL,
  PRIMARY KEY (`InvoiceID`),
  CONSTRAINT `fk_Invoice_Event1`
    FOREIGN KEY (`EventID`)
    REFERENCES `mydb`.`Event` (`EventID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoice_Customer1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `mydb`.`Customer` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
